### ISSUE TITLE
it's published

### ISSUE THREAD

**Issue by ttriche** [mtekman/HaploForge#2]
https://academic.oup.com/bioinformatics/article-abstract/doi/10.1093/bioinformatics/btx510/4082271/HaploForge-A-Comprehensive-Pedigree-Drawing-and

time to update the README ;-)

Best,
--t

**Comment by mtekman** [comment]
Updated, thank you kindly!

**Comment by ttriche** [comment]
This will be very handy for some projects of mine, the least I could do is
point out that it's been published :-)

Take care,


--t

**Comment by mtekman** [comment]
Glad to hear it!

Please let me know of any bugs or requests that you may encounter ;-)
