### ISSUE TITLE
No working with my allegro's data

### ISSUE THREAD

**Issue by alexmathieu** [mtekman/HaploForge#9]
Hi,

When I submit my allegro files, nothing is displayed.
[Archive.zip](https://github.com/mtekman/HaploForge/files/1841203/Archive.zip)

Thanks per advance.

**Comment by mtekman** [comment]
Hi @alexmathieu, HaploForge at the moment only expects numeric data for patient IDs.

Your `ihaplo.out` and `founder.out` contain IDs that begin with the letter 'I'.

I got your data working by replacing the 'I' with '99'.

    cat ihaplo.out | sed 's/\bI/99/g' > ihaplo.fixed.out
    cat founder.out | sed 's/\bI/99/g' > founder.fixed.out

Please let me know if you have further issues!

**Comment by alexmathieu** [comment]
Thx !!!!
